package pong_game.Grafiikka;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import pong_game.Grafiikka.Nappaimet.KlikkaustenKuuntelija;
import pong_game.Grafiikka.Nappaimet.KlikkaustenKuuntelijaAsetukset;
import pong_game.Grafiikka.Nappaimet.KlikkaustenKuuntelijaAsetukset;
import pong_game.Oliot.Maila;
import pong_game.Oliot.Pallo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tommi
 */
public class Paavalikko2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Paavalikko2(Maila yksi, Maila kaksi, Pallo pallo) {
        // this.getContentPane().setBackground(Color.blue);
        initComponents();
        this.pallo = pallo;
        this.yksi = yksi;
        this.kaksi = kaksi;
        nappaimet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelaa = new javax.swing.JButton();
        asetukset = new javax.swing.JButton();
        lopeta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pelaa.setText("pelaa");

        asetukset.setText("Asetukset");

        lopeta.setText("Lopeta");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tommi\\Desktop\\pong_game_menu.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pelaa, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(asetukset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lopeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pelaa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(asetukset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lopeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private Pallo pallo;
    private Maila yksi;
    private Maila kaksi;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asetukset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lopeta;
    private javax.swing.JButton pelaa;
    // End of variables declaration//GEN-END:variables
 public void nappaimet() {
        KlikkaustenKuuntelija kopioija = new KlikkaustenKuuntelija(pelaa, asetukset, lopeta,this , yksi, kaksi, pallo);
        pelaa.addActionListener(kopioija);
        asetukset.addActionListener(kopioija);
        lopeta.addActionListener(kopioija);
    }

 
}
